### PR TITLE
Update the examples as per Minishift v1.7.0

### LINKED ISSUE #4: Update the examples to Minishift version 1.0.0
We have now [Minishift 1.0.0](https://github.com/minishift/minishift/releases/tag/v1.0.0) released around 10 days ago.

Also, it uses the OpenShift version `1.5.0` which has Kubernetes `1.5.2`.

Happy to look into it :smile:

### PR DESCRIPTION
**Pull request by budhrg**
Fix #4

### CODE REVIEW

**Comment by mhausenblas** [comment]
Thanks a lot for this PR @budhrg and sorry for the delay, been on travel. Overall looks good, but there's one issue I'd like you to ask to fix (or we wait until I update it to Kube 1.7 later this year, up to you). You're using  in a number of places `minishift ssh` or other Minishift-specific idioms. Now, while the examples are done with Minishift, this is not a Minishift-specific by-example site but a general Kubernetes one so we should not introduce such implementation-specific details unless there is a good reason for it. Hope this makes sense?

**Comment by budhrg** [comment]
> ou're using in a number of places minishift ssh or other Minishift-specific idioms. Now, while the examples are done with Minishift, this is not a Minishift-specific by-example site but a general Kubernetes one so we should not introduce such implementation-specific details unless there is a good reason for it. Hope this makes sense?

Make sense :+1: 

Updated the PR @mhausenblas Thanks

**Comment by mhausenblas** [comment]
Awesome, thanks a lot!

**Comment by budhrg** [comment]
> Awesome, thanks a lot!

My pleasure :smile:

**Comment by budhrg** [comment]
@mhausenblas , you forgot to update the website again :wink: 

screenshot from 2017-10-25 11-34-50

**Comment by mhausenblas** [comment]
Geez, when will I ever learn. Guess we should automate that process ;)

Done!

**Comment by budhrg** [comment]
> Geez, when will I ever learn. Guess we should automate that process ;)

That would be awesome @mhausenblas  :+1:

**Pull request merged**
